default:
  path_user: "data-raw/user.csv"
  path_tone: "data-raw/tone.csv"

  path_user_info: "data-raw/user-info.csv"

  path_ratio_last_scrape: "data/ratio-last-scrape.csv"
  path_ratio_first_scrape: "data/ratio-first-scrape.csv" # TODO
  path_ratio_log_scrape: "data/ratio-log-scrape.csv"
  path_tl_cache: "data/tl-cache.csv"

  path_ratio_last_post: "data/ratio-last-post.csv"
  # path_ratio_last_post: "data/ratio-first-post.csv"

  # Note: `path_ratio_log_post` is not currently used.
  # path_ratio_log_post: "data/ratio-log-post.csv"

  n_hour_lag_scrape: 12
  n_tl_new: 100
  # n_tl_since: 1000
  n_tl_until: 1000

  tl_cache: false

  scrape_reply_sentinel: -42

  # TODO: Implement these.
  post_n_since_min: 10
  post_hour_since_min: 23
  # post_retweet_min: 25
  # post_favorite_min: 25
  # post_ratio_den_min: 50 # retweet + favorite
  # post_ratio_num_min: 10 # reply
  post_ratio_den_min_frac: 0.0001
  # post_ratio_num_min_frac: 0.0001
  post_ratio_min: 0.25

  # Note: `post` prevents the `.create_post()` function from being called.
  # Note: It is recommended to set this to true and leave the other `post_*` parameters
  # as they would otherwise be defined.
  # post: true
  post: false

  # Note: `post_status_id_sentinel` allows for the `.create_post()` function to be called, and is used
  # in the case that the `post_reply`, `post_retweet`, and `post_favorite` are all
  # set to `false` (i.e. nothing is posted). In this case, this value
  # tells the program not to record anything as "posted" (even though `text_post`
  # is generated). It will cause the program to revert potential updates to the
  # data in `path_ratio_log_scrape` and `path_ratio_last_post`.
  # Additionally, this value supplements the usage of `post` = `true`, so that
  # actions that would occur after posting a tweet get run. This is useful
  # for checking that the code would work when it comes time to actually make the post.
  post_status_id_sentinel: "-42"

  post_reply: true
  post_retweet: true
  post_favorite: true

  verbose_scrape: true
  verbose_post: true
  verbose_regenerate: true

  # TODO
  progress_scrape: true
  progress_post: true

  # TODO: Break up these into more specific components?
  verbose_file: false
  backup_file: true

  backup_scrape: true
  backup_post: true

  # token: !expr rtweet::get_token()

production:

