default:
  path_screen_name: "data-raw/screen_name.csv"
  path_ratio_last_scrape: "data/ratio-last-scrape.csv"
  path_ratio_log: "data/ratio-log.csv"
  path_tl_cache: "data/tl-cache.csv"
  path_ratio_last_post: "data/ratio-last-post.csv"

  n_hour_lag_scrape: 12
  n_tl_new: 1000

  cache_tl: false

  post_reply: true
  post_retweet: false
  post_favorite: true

  verbose_scrape: true
  verbose_post: true
  verbose_file: false
  backup_file: true

  token: !expr rtweet::get_token()

production:

